config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :courses do
    resources :lessons
  end
  resources :lessons

  resources :examinations do
    resources :questions
  end

  post '/examinations/:id/check', to: 'examinations#check', as: 'examination_check'

  resources :questions do
    resources :answers
  end

  get '/profile', to: 'pages#profile', as: 'page_profile'
  get '/profile-courses', to: 'pages#profile_courses', as: 'page_profile_courses'
  get '/calendar', to: 'pages#calendar', as: 'page_calendar'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :lessons, dependent: :destroy
end

app/models/examination.rb
class Examination < ApplicationRecord
  has_many :questions
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :course
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :examination
  has_many :answers
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.create(answer_params)
    redirect_to question_path(@question)
  end

  def destroy
    @question = Question.find(params[:question_id])
    @answer = @question.answers.find(params[:id])
    @answer.destroy
    redirect_to question_path(@question)
  end

  def edit
    @question = Question.find(params[:question_id])
    @answer = @question.answers.find(params[:id])
  end

  def update
    @question = Question.find(params[:question_id])
    @answer = @question.answers.find(params[:id])

    respond_to do |format|
      if @examination.update(examination_params)
        format.html { redirect_to @examination, notice: 'Exam was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:title, :correct)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[ show edit update destroy ]

  def index
    @courses = Course.all
  end

  def show; end

  def new
    @course = Course.new
  end

  def edit; end

  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: "Course was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: "Course was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: "Course was successfully destroyed." }
    end
  end

  private

  def set_course
    @course = Course.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:title, :description)
  end
end

app/controllers/examinations_controller.rb
class ExaminationsController < ApplicationController
  def index
    @examinations = Examination.all
  end

  def show
    @examination = Examination.find(params[:id])
  end

  def new
    @examination = Examination.new
  end

  def edit
    @examination = Examination.find(params[:id])
  end

  def create
    @examination = Examination.new(examination_params)

    respond_to do |f|
      if @examination.save
        f.html { redirect_to @examination, notice: 'Examination was successfully created.' }
      else
        f.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    @examination = Examination.find(params[:id])

    respond_to do |f|
      if @examination.update(examination_params)
        f.html { redirect_to @examination, notice: 'Examination was successfully updated.' }
      else
        f.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @examination = Examination.find(params[:id])
    @examination.destroy

    redirect_to examinations_path
  end

  def check
    @examination = Examination.find(params[:id])
    @answers = params[:examination][:answer]

    correct = 0
    @answers.each do |k, v|
      @check = Answer.find(k)
      @check.correct && v['title'] == '1' && correct += 1
    end
    respond_to do |f|
      f.html { redirect_to @examination, notice: "#{correct} of #{@examination.questions.length}" }
    end
  end

  private

  def examination_params
    params.require(:examination).permit(:title)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: %i[ show edit update destroy ]

  # GET /lessons or /lessons.json
  def index
    @lessons = Lesson.all
  end

  # GET /lessons/1 or /lessons/1.json
  def show
  end

  # GET /lessons/new
  def new
    @lesson = Lesson.new
  end

  # GET /lessons/1/edit
  def edit
  end

  # POST /lessons or /lessons.json
  def create
    @lesson = Lesson.new(lesson_params)

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to @lesson, notice: "Lesson was successfully created." }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessons/1 or /lessons/1.json
  def update
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to @lesson, notice: "Lesson was successfully updated." }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1 or /lessons/1.json
  def destroy
    @lesson.destroy
    respond_to do |format|
      format.html { redirect_to lessons_url, notice: "Lesson was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def lesson_params
      params.require(:lesson).permit(:title, :description, :course_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def profile
    respond_to do |format|
      format.html { render :profile }
    end
  end

  def profile_courses
    respond_to do |format|
      format.html { render :profile_courses }
    end
  end

  def calendar
    respond_to do |format|
      format.html { render :calendar }
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
  end

  def new
    @question = Question.new
  end

  def edit
    @question = Question.find(params[:id])
  end

  def create
    @question = Question.create(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  private

  def question_params
    params.require(:question).permit(:title, :examination_id)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/examinations_helper.rb
module ExaminationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_answer.html.erb
<div>
  <%= answer.title %>
  <% if answer.correct %>
    &#9989;
  <% else %>
    &#10060;
  <% end %>
</div>

<p>
  <%= link_to 'Редактировать', edit_question_answer_path(answer.question, answer) %>
  <%= link_to 'Удалить ответ', [answer.question, answer],
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
</p>

app/views/answers/_form.html.erb
<%= form_with model: [@question, @question.answers.build] do |form| %>
  <div class="card">
    <div class="card-body">
      <div class="mb-3">
        <%= form.label :title, class: 'form-label' %>
        <%= form.text_field :title, {class: 'form-control'} %>
      </div>

      <div class="mb-3">
        <div class="form-check">
          <%= form.check_box :correct, class: 'form-check-input' %>
          <%= form.label :correct, class: 'form-check-label' %>
        </div>
      </div>

      <div class="mb-3">
        <%= form.submit 'Добавить вопрос', class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
<% end %>

app/views/answers/edit.html.erb
<section class="container">
  <h1>Редактировать ответ</h1>

  <%= form_with model: [@question, @answer] do |form| %>
    <div class="card">
      <div class="card-body">
        <div class="mb-3">
          <%= form.label :title, class: 'form-label' %>
          <%= form.text_field :title, {class: 'form-control'} %>
        </div>

        <div class="mb-3">
          <div class="form-check">
            <%= form.check_box :correct, class: 'form-check-input' %>
            <%= form.label :correct, class: 'form-check-label' %>
          </div>
        </div>

        <div class="mb-3">
          <%= form.submit 'Обновить ответ', class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
  <% end %>

  <div class="flex">
    <%#= link_to 'Назад', question_path(@answer.question), class: "btn btn-link" %>
  </div>
</section>

app/views/courses/_form.html.erb
<%= form_with(model: course) do |form| %>
  <div class="card mb-4">
    <div class="card-body">
      <% if course.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

          <ul>
            <% course.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="mb-3">
        <%= form.label :title, 'Название', class: "form-label" %>
        <%= form.text_field :title, { class: "form-control" } %>
      </div>

      <div class="mb-3">
        <%= form.label :description, 'Описание', class: "form-label" %>
        <%= form.text_area :description, { class: "form-control" } %>
      </div>

      <%= form.submit "Создать", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/courses/edit.html.erb
<section class="container py-4">
  <h1>Редактировать курс</h1>

  <%= render 'form', course: @course %>

  <div class="flex">
    <%= link_to 'Показать', @course, class: "btn btn-link" %>
    <%= link_to 'Назад', courses_path, class: "btn btn-link" %>
  </div>
</section>

app/views/courses/index.html.erb
<section class="container py-4">
  <%= render partial: "shared/notice", notice: notice %>

  <h1>Курсы</h1>

  <table class="table">
    <thead>
    <tr>
      <th>Id</th>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.id %></td>
        <td><%= course.title %></td>
        <td><%= link_to 'Показать', course %></td>
        <td><%= link_to 'Редактировать', edit_course_path(course) %></td>
        <td><%= link_to 'Удалить', course, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Добавить курс', new_course_path, class: 'btn btn-primary' %>
</section>

app/views/courses/new.html.erb
<section class="container py-4">
  <h1>Добавить новый курс</h1>

  <%= render 'form', course: @course %>
  <%= link_to 'Назад', courses_path, class: "btn btn-link" %>
</section>

app/views/courses/show.html.erb
<section class="container py-4">
  <%= render partial: "shared/notice", notice: notice %>

  <h1>
    <%= @course.title %>
  </h1>

  <div class="row">
    <div class="col col-md-3">
      <div class="card">
        <div class="card-header">
          Меню
        </div>
        <ul class="list-group list-group-flush">
          <% @course.lessons.each do |lesson| %>
            <li class="list-group-item">
              <%= link_to lesson.title, course_lesson_path(@course, lesson), class: "card-link" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="col">
      <div>
        <%= @course.description %>
      </div>
      <div class="flex pt-4">
        <%= link_to 'Учить', course_lesson_path(@course, @course.lessons.first), class: 'btn btn-primary' %>
      </div>
    </div>
  </div>

  <div class="flex pt-4">
    <%= link_to 'Редактировать', edit_course_path(@course), class: 'btn btn-primary' %>
    <%= link_to 'Назад', courses_path, class: 'btn btn-link' %>
  </div>
</section>

app/views/examinations/_form.html.erb
<%= form_with(model: examination) do |form| %>
  <div class="card mb-4">
    <div class="card-body">
      <% if examination.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(examination.errors.count, "error") %> prohibited this exam from being saved:</h2>

          <ul>
            <% examination.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="mb-3">
        <%= form.label :title, 'Название', class: "form-label" %>
        <%= form.text_field :title, { class: "form-control" } %>
      </div>

      <%= form.submit "Отправить", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/examinations/edit.html.erb
<section class="container py-4">
  <h1>Редактировать экзамен</h1>

  <%= render 'form', examination: @examination %>

  <div class="flex">
    <%= link_to 'Показать', @examination, class: "btn btn-primary" %>
    <%= link_to 'Назад', examination_path, class: "btn btn-link" %>
  </div>
</section>

app/views/examinations/index.html.erb
<section class="container py-4">
  <%= render partial: "shared/notice", notice: notice %>

  <h1>Экзамены</h1>

  <table class="table">
    <thead>
    <tr>
      <th>ID</th>
      <th>Название</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @examinations.each do |exam| %>
      <tr>
        <td><%= exam.id %></td>
        <td><%= exam.title %></td>
        <td><%= link_to 'Показать', exam %></td>
        <td><%= link_to 'Редактировать', edit_examination_path(exam) %></td>
        <td><%= link_to 'Удалить', exam, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Добавить экзамен', new_examination_path, class: 'btn btn-primary' %>
</section>

app/views/examinations/new.html.erb
<section class="container py-4">
  <h1>Добавить новый экзамен</h1>

  <%= render 'form', examination: @examination %>
  <%= link_to 'Назад', examinations_path, class: "btn btn-link" %>
</section>

app/views/examinations/show.html.erb
<section class="container py-4">
  <%= render partial: "shared/notice", notice: notice %>

  <h1>
    <%= @examination.title %>
  </h1>

  <h4 class="mb-3">Вопросы</h4>

  <div>
    <%= form_with model: @examination, url: examination_check_path(@examination), method: "post" do |exam_form| %>
      <% @examination.questions.each do |question| %>
        <%= exam_form.fields_for question, index: question.id do |question_form| %>
          <div class="mb-3">
            <h6><%= question.title %></h6>
            <% question.answers.each do |answer| %>
              <%= exam_form.fields_for answer, index: answer.id do |answer_form| %>
                <div class="form-check">
                  <%= answer_form.check_box :title, class: 'form-check-input' %>
                  <%= answer_form.label :title, "#{answer.title}", class: 'form-check-label' %>
                </div>
              <% end %>
            <% end %>
          </div>
        <% end %>
      <% end %>
      <%= exam_form.submit "Отправить", class: "btn btn-primary" %>
    <% end %>
  </div>

  <div class="flex pt-4">
    <%= link_to 'Редактировать', edit_examination_path(@examination), class: 'btn btn-primary' %>
    <%= link_to 'Назад', examinations_path, class: 'btn btn-link' %>
  </div>
</section>

app/views/home/index.html.erb
<div class="home-hero py-5">
  <div class="container">
    <div class="row my-5">
      <div class="col col-lg-6 my-5">
        <h1>Добро пожаловать <br> в наш онлайн университет</h1>
        <%= link_to "Приступить к обучению", root_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col col-md-8">
      <h2>Impulse LMS</h2>
      <p>Не следует, однако забывать, что дальнейшее развитие различных форм деятельности позволяет оценить значение
        позиций, занимаемых участниками в отношении поставленных задач. Таким образом реализация намеченных плановых
        заданий позволяет оценить значение дальнейших направлений развития. Значимость этих проблем настолько очевидна,
        что новая модель организационной деятельности обеспечивает широкому кругу (специалистов) участие в формировании
        существенных финансовых и административных условий.</p>
    </div>
  </div>
</div>

app/views/lessons/_form.html.erb
<%= form_with(model: lesson) do |form| %>
  <div class="card mb-4">
    <div class="card-body">
      <% if lesson.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(lesson.errors.count, "error") %> prohibited this lesson from being saved:</h2>

          <ul>
            <% lesson.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="mb-3">
        <%= form.label :title, 'Название', class: "label" %>
        <%= form.text_field :title, { class: "form-control" } %>
      </div>

      <div class="mb-3">
        <%= form.label :description, 'Описание', class: "label" %>
        <%= form.text_area :description, { class: "form-control" } %>
      </div>

      <div class="mb-3">
        <%= form.label :course_id, 'Курс', class: "label" %>
        <%= collection_select(:lesson, :course_id, Course.all.collect, :id, :title, { prompt: true }, { class: "form-control" }) %>
      </div>

      <div>
        <%= form.submit 'Создать', class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/lessons/edit.html.erb
<section class="container py-4">
  <h1>Редакатировать урок</h1>

  <%= render 'form', lesson: @lesson %>

  <div class="flex">
    <%#= link_to 'Сохранить', @lesson, class: 'btn btn-primary' %>
    <%= link_to 'Назад', lessons_path, class: 'btn btn-link' %>
  </div>
</section>

app/views/lessons/index.html.erb
<section class="container py-4">
  <%= render partial: "shared/notice", notice: notice %>

  <h1>Уроки</h1>

  <table class="table">
    <thead>
    <tr>
      <th>ID</th>
      <th>Название</th>
      <th>Курс</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @lessons.each do |lesson| %>
      <tr>
        <td><%= lesson.id %></td>
        <td><%= lesson.title %></td>
        <td><%= lesson.course_id %></td>
        <td><%= link_to 'Показать', lesson %></td>
        <td><%= link_to 'Редакатировать', edit_lesson_path(lesson) %></td>
        <td><%= link_to 'Удалить', lesson, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Новый урок', new_lesson_path, class: 'btn btn-primary' %>

</section>

app/views/lessons/new.html.erb
<section class="container py-4">
  <h1>Новый урок</h1>

  <%= render 'form', lesson: @lesson %>

  <%= link_to 'Назад', lessons_path, class: 'btn btn-link' %>
</section>

app/views/lessons/show.html.erb
<section class="container py-4">
  <%= render partial: "shared/notice", notice: notice %>

  <h1>
    <%= @lesson.course.title %>
  </h1>

  <div class="row">
    <div class="col col-md-3">
      <div class="card">
        <div class="card-header">
          Меню
        </div>
        <ul class="list-group list-group-flush">
          <% @lesson.course.lessons.each do |lesson| %>
            <li class="list-group-item">
              <%= link_to lesson.title, course_lesson_path(@lesson.course, lesson), class: "card-link" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="col">
      <h2><%= @lesson.title %></h2>
      <div>
        <%= @lesson.description %>
      </div>
    </div>
  </div>

  <div class="flex pt-4">
    <%= link_to 'Редактировать', edit_lesson_path(@lesson), class: 'btn btn-primary' %>
    <%= link_to 'Назад', courses_path, class: 'btn btn-link' %>
  </div>
</section>

app/views/questions/_form.html.erb
<%= form_with(model: question) do |form| %>
  <div class="card mb-4">
    <div class="card-body">
      <% if question.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

          <ul>
            <% question.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="mb-3">
        <%= form.label :title, 'Название', class: "form-label" %>
        <%= form.text_field :title, { class: "form-control" } %>
      </div>

      <div class="mb-3">
        <%= form.label :examination_id, 'Экзамен', class: "label" %>
        <%= collection_select(:question, :examination_id, Examination.all.collect, :id, :title, { prompt: true }, { class: "form-control" }) %>
      </div>

      <%= form.submit "Создать", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/questions/edit.html.erb
<section class="container py-4">
  <h1>Редактировать вопрос</h1>

  <%= render 'form', question: @question %>

  <div class="flex">
    <%= link_to 'Показать', @question, class: "btn btn-primary" %>
    <%= link_to 'Назад', questions_path, class: "btn btn-link" %>
  </div>
</section>

app/views/questions/index.html.erb
<section class="container py-4">
  <%= render partial: "shared/notice", notice: notice %>

  <h1>Вопросы</h1>

  <table class="table">
    <thead>
    <tr>
      <th>Id</th>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.id %></td>
        <td><%= question.title %></td>
        <td><%= link_to 'Показать', question %></td>
        <td><%= link_to 'Редактировать', edit_question_path(question) %></td>
        <td><%= link_to 'Удалить', question, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Добавить вопрос', new_question_path, class: 'btn btn-primary' %>
</section>

app/views/questions/new.html.erb
<section class="container py-4">
  <h1>Добавить новый вопрос</h1>

  <%= render 'form', question: @question %>
  <%= link_to 'Назад', questions_path, class: "btn btn-link" %>
</section>

app/views/questions/show.html.erb
<section class="container py-4">
  <%= render partial: "shared/notice", notice: notice %>

  <h1>
    <%= @question.title %>
  </h1>

  <h5>Вопросы</h5>
  <div>
    <%= render @question.answers %>
  </div>

  <h5>Добавить ответ</h5>
  <div>
    <%= render 'answers/form' %>
  </div>

  <div class="flex pt-4">
    <%= link_to 'Редактировать', edit_question_path(@question), class: 'btn btn-primary' %>
    <%= link_to 'Назад', questions_path, class: 'btn btn-link' %>
  </div>
</section>