config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :courses do
    resources :lessons
  end
  resources :lessons

  resources :examinations do
    resources :questions
  end

  post '/examinations/:id/check', to: 'examinations#check', as: 'examination_check'

  resources :questions do
    resources :answers
  end

  get '/profile', to: 'pages#profile', as: 'page_profile'
  get '/profile-courses', to: 'pages#profile_courses', as: 'page_profile_courses'
  get '/calendar', to: 'pages#calendar', as: 'page_calendar'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :lessons, dependent: :destroy
end

app/models/examination.rb
class Examination < ApplicationRecord
  has_many :questions
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :course
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :examination
  has_many :answers
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.create(answer_params)
    redirect_to question_path(@question)
  end

  def destroy
    @question = Question.find(params[:question_id])
    @answer = @question.answers.find(params[:id])
    @answer.destroy
    redirect_to question_path(@question)
  end

  def edit
    @question = Question.find(params[:question_id])
    @answer = @question.answers.find(params[:id])
  end

  def update
    @question = Question.find(params[:question_id])
    @answer = @question.answers.find(params[:id])

    respond_to do |format|
      if @examination.update(examination_params)
        format.html { redirect_to @examination, notice: 'Exam was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:title, :correct)
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[ show edit update destroy ]

  def index
    @courses = Course.all
  end

  def show; end

  def new
    @course = Course.new
  end

  def edit; end

  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: "Course was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: "Course was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: "Course was successfully destroyed." }
    end
  end

  private

  def set_course
    @course = Course.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:title, :description)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: %i[ show edit update destroy ]

  # GET /lessons or /lessons.json
  def index
    @lessons = Lesson.all
  end

  # GET /lessons/1 or /lessons/1.json
  def show
  end

  # GET /lessons/new
  def new
    @lesson = Lesson.new
  end

  # GET /lessons/1/edit
  def edit
  end

  # POST /lessons or /lessons.json
  def create
    @lesson = Lesson.new(lesson_params)

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to @lesson, notice: "Lesson was successfully created." }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessons/1 or /lessons/1.json
  def update
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to @lesson, notice: "Lesson was successfully updated." }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1 or /lessons/1.json
  def destroy
    @lesson.destroy
    respond_to do |format|
      format.html { redirect_to lessons_url, notice: "Lesson was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def lesson_params
      params.require(:lesson).permit(:title, :description, :course_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def profile
    respond_to do |format|
      format.html { render :profile }
    end
  end

  def profile_courses
    respond_to do |format|
      format.html { render :profile_courses }
    end
  end

  def calendar
    respond_to do |format|
      format.html { render :calendar }
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
  end

  def new
    @question = Question.new
  end

  def edit
    @question = Question.find(params[:id])
  end

  def create
    @question = Question.create(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  private

  def question_params
    params.require(:question).permit(:title, :examination_id)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/examinations_helper.rb
module ExaminationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/_footer.html.erb
<div class="container">
  <div class="row align-items-center">
    <div class="col">
      Copyright 2021
    </div>
    <div class="col text-end">
      <a href="https://github.com/codev0/rails-lms" class="display-6">
        <i class="bi bi-github"></i>
      </a>
    </div>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <%= link_to "Impulse LMS", root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Главная", root_path, { class: "nav-link" } %>
        </li>
        <li class="nav-item">
          <%= link_to "Мои курсы", courses_path, { class: "nav-link" } %>
        </li>
        <li class="nav-item">
          <%= link_to "Профиль", page_profile_path, { class: "nav-link" } %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-100 no-touch">
<head>
  <title>Impulse LMS</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
</head>
<body class="d-flex flex-column h-100">
<header>
  <%= render 'layouts/navigation' %>
</header>
<main class="flex-shrink-0">
  <%= yield %>
</main>
<footer class="footer mt-auto py-3 bg-light">
  <%= render 'layouts/footer' %>
</footer>
</body>
</html>

app/views/pages/_card.html.erb
<div class="card">
  <div class="card-header">
    Меню
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">
      <%= link_to "Профиль", page_profile_path %>
    </li>
    <li class="list-group-item">
      <%= link_to "Курсы", page_profile_courses_path %>
    </li>
    <li class="list-group-item">
      <%= link_to "События", page_calendar_path %>
    </li>
    <li class="list-group-item">
      <%= link_to "Выйти", root_path %>
    </li>
  </ul>
</div>

app/views/pages/calendar.html.erb
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/fullcalendar@5.7.2/main.min.css">
<script src="https://cdn.jsdelivr.net/npm/fullcalendar@5.7.2/main.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fullcalendar@5.7.2/locales-all.min.js"></script>
<script>
    document.addEventListener('turbolinks:load', function () {
        var calendarEl = document.getElementById('calendar');
        var calendar = new FullCalendar.Calendar(calendarEl, {
            initialView: 'dayGridMonth',
            locale: 'ru',
        });
        calendar.render();
    });
</script>

<div class="container py-4">
  <div id='calendar'></div>
</div>

app/views/pages/profile.html.erb
<div class="container py-4">
  <h1>Профиль</h1>
  <div class="row">
    <div class="col col-md-3">
    <%= render 'pages/card' %>
    </div>
    <div class="col">
      <h2>Жаншуаков Айрат Кайратович</h2>
      <img src="https://www.fillmurray.com/120/120" class="img-thumbnail" alt="...">
      <p>
        Не следует, однако забывать, что дальнейшее развитие различных форм деятельности позволяет оценить значение
        позиций, занимаемых участниками в отношении поставленных задач. Таким образом реализация намеченных плановых
        заданий позволяет оценить значение дальнейших направлений развития. Значимость этих проблем настолько очевидна,
        что новая модель организационной деятельности обеспечивает широкому кругу (специалистов) участие в формировании
        существенных финансовых и административных условий.
      </p>
    </div>
  </div>
</div>

app/views/pages/profile_courses.html.erb
<div class="container py-4">
  <h1>Курсы</h1>
  <div class="row">
    <div class="col col-md-3">
      <%= render 'pages/card' %>
    </div>
    <div class="col">
      <h2>Ваши курсы</h2>
      <div class="d-flex justify-content-between mb-2">
        <span>Базы данных</span><span>В прогрессе</span>
      </div>
      <div class="d-flex justify-content-between mb-2">
        <span>Платформа .NET</span><span>82 балла</span>
      </div>
      <div class="d-flex justify-content-between mb-2">
        <span>Веб дизайн</span><span>40 баллов</span>
      </div>
    </div>
  </div>
</div>

app/views/shared/_notice.html.erb
<% if notice %>
  <div class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% end %>